---
- name: Instalace vanilla Windows
  hosts: "{{ seznam_stanic }}"
  
  tasks:
   - name: Kopírování instalační složky Office
     win_copy: 
      src: "{{ cesta_src_office }}"
      dest: "{{ cesta_dest_office }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only 
   
 #  - name: Nainstaluje Office
 #    win_command: 'C:\Ansible\temp\Windows_Office_autoinstall_64bit\setup.exe'
   
   
   - name: Nainstaluje Office
     win_package:
       path: "{{ cesta_office }}"
       product_id: MSOffice
       expected_return_code: [0, 3010]
       state: present
       
 #  - name: Smaže instalační soubory
 #    win_file: 
 #     path: "{{ cesta_dest_office }}"
 #     state: absent

   - name: Install z Chocolatey - Chrome
     win_chocolatey: 
      name: googlechrome
      state: present
      
   - name: Install z Chocolatey - Mozzila Firefox
     win_chocolatey: 
      name: firefox
      state: present
   
   - name: Install z Chocolatey - Adobe Reader
     win_chocolatey: 
      name: adobereader
      state: present
      
   - name: Install z Chocolatey - 7zip
     win_chocolatey: 
      name: 7zip.install
      state: present
   
   - name: Install z Chocolatey - OpenVPN
     win_chocolatey: 
      name: OpenVPN
      state: present
   
   - name: Install z Chocolatey - Notepad++
     win_chocolatey: 
      name: notepadplusplus
      state: present
   
   - name: Instalace Avast
     win_package:
       path: "{{ cesta_instalacniho_souboru }}"
       product_id: "{{ id_produktu }}"
       state: present
     vars: 
       ansible_become: yes
       ansible_become_method: runas
       ansible_become_user: "{{ superucet }}"
       ansible_become_pass: "{{ superheslo }}"
       ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
   
   - name: Přizpůsobení VPN
     win_copy: 
      src: "{{ cesta_src }}"
      dest: "{{ cesta_dest }}"
      remote_src: yes
     vars: 
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "{{ superucet }}"
      ansible_become_pass: "{{ superheslo }}"
      ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only 

 #  - name: "Updatuje Windows"
 #    win_updates:
 #     # category_names: "{{ kategorie }}"
 #      log_path: "{{ cesta_update_logu }}"      #c:\Ansible\update_log.txt
 #    register: win_update_results
 #    failed_when: win_update_results.failed is defined and win_update_results.failed and win_update_reboot == False

 #  - name: "Restart, pokud je potřeba"
 #    win_reboot:
 #      shutdown_timeout_sec: 600
 #      reboot_timeout_sec: 600
 #    when: win_update_results.reboot_required is defined and win_update_results.reboot_required == True and win_update_reboot
