---
- name: Instalace vanilla Windows
  hosts: "{{ seznam_stanic }}"
  
  tasks:
   - name: Nainstaluje Office
     win_package:
       path: "{{ cesta_office }}"
       ansible_become: yes
       ansible_become_user: "{{ superucet }}"
       ansible_become_pass: "{{ superheslo }}"
       product_id: "{{ id_produktu }}"
       state: present

   - name: Nainstaluje Avast
     win_package:
       path: "{{ cesta_avast }}"
       ansible_become: yes
       ansible_become_user: "{{ superucet }}"
       ansible_become_pass: "{{ superheslo }}"
       product_id: "{{ id_produktu }}"
       state: present

   - name: Nainstaluje Chrome
     win_package:
       path: "{{ cesta_chrome }}"
       ansible_become: yes
       ansible_become_user: "{{ superucet }}"
       ansible_become_pass: "{{ superheslo }}"
       product_id: "{{ id_produktu }}"
       state: present

   - name: "Updatuje Windows"
     win_updates:
       category_names: "{{ kategorie }}"
       log_path: "{{ cesta_update_logu }}"      #c:\Ansible\update_log.txt
     register: win_update_results
     failed_when: win_update_results.failed is defined and win_update_results.failed and win_update_reboot == False

   - name: "Restert, pokud je potřeba"
     win_reboot:
       shutdown_timeout_sec: 600
       reboot_timeout_sec: 600
     when: win_update_results.reboot_required is defined and win_update_results.reboot_required == True and win_update_reboot
